#!/usr/bin/env python
import sys,os,re

def shquote(data):
  data=re.sub(r'["\\]',r'\\\1',data)
  data='"%s"'%data
  return data

user_agent='-U '+shquote('Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1)')

# forge referer
referer=[v for v in sys.argv[1:] if 'http://' in v]
if referer:
  referer='--referer='+shquote(referer[0])
else:
  referer=''

# forge argv
argv=[shquote(v) for v in sys.argv[1:]]
argv=' '.join(argv)

# forge cmd
cmd='wget -Ajpg,JPG,gif,GIF -l1 -nd -e robots=off -r %(user_agent)s %(referer)s %(argv)s'
cmd=cmd%locals()

print cmd
os.system(cmd)
