#!/bin/bash
for VID; do
  WAV="${VID%.*}.wav"
  MP3="${VID%.*}.mp3"
  echo "# Encoding $VID to $WAV"
  vlc -I dummy  \
   --sout="#transcode{acodec=s16l}:standard{access=file,mux=wav,dst=\"$WAV\"}" \
   "$VID" vlc://quit
  echo "# Encoding $WAV to $MP3"
  lame -h "$WAV" "$MP3" && rm "$WAV"
done
#transcode{vcodec=mpeg,vb=800,acodec=mp3,ab=128,maxwidth=800,maxheight=600}
#--sout="#transcode{acodec=mp3}:standard{access=file,mux=raw,dst=\"$MP3\"}" \
