#!/bin/bash
for VID; do
  AVI="${VID%.*}.avi"
  echo "# Encoding $VID to $AVI"
  vlc -I dummy  \
   --sout="#transcode{acodec=copy;vcodec=xvid}:standard{access=file,mux=avi,dst=\"$AVI\"}" \
   "$VID" vlc://quit
done
#transcode{vcodec=mpeg,vb=800,acodec=mp3,ab=128,maxwidth=800,maxheight=600}
#--sout="#transcode{acodec=mp3}:standard{access=file,mux=raw,dst=\"$MP3\"}" \
